%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------
File.version: "1.0"
Camera.type: "PinHole"

#--------------------------------------------------------------------------------------------
# Camera Parameters (Gazebo camera_info'dan)
#--------------------------------------------------------------------------------------------
Camera1.fx: 381.36246688113556
Camera1.fy: 381.36246688113556
Camera1.cx: 320.5
Camera1.cy: 240.5

# Distortion (gazebo camera_info D: hepsi 0)
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera.width: 640
Camera.height: 480

# İstersen aynı kalsın
Camera.newWidth: 640
Camera.newHeight: 480

# Gazebo görüntü akışı ~20-30; burada 30 yazmak sorun olmaz
Camera.fps: 30

# Gazebo genelde RGB üretir ama rostopic'teki encoding'e göre gerekirse değiştiririz
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
