%YAML:1.0

# =========================
# Monocular Webcam Template
# =========================
Camera.type: "PinHole"

# Webcam publish ayarına göre değiştir (şimdilik 640x480)
Camera.width: 640
Camera.height: 480

# Geçici intrinsics (kalibrasyondan sonra güncellenecek)
Camera.fx: 484.4355345057132
Camera.fy: 482.8885736238781
Camera.cx: 319.3072820300305
Camera.cy: 240.509939059061

# Distortion (kalibrasyondan sonra doldur)
Camera.k1: 0.047346596412790994
Camera.k2: -0.06644363334228547
Camera.p1: 0.0008588223531509833
Camera.p2: 0.00019802975564182348
Camera.k3: 0.0

Camera.fps: 30.0
Camera.RGB: 0   # 0=BGR, 1=RGB

# ORB Extractor
ORBextractor.nFeatures: 1200
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 12
ORBextractor.minThFAST: 5

# Viewer (pangolin kapalı olsa bile kalsın)
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 1
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 2
